feat: Patch rnfs to handle 303 http code on download
cozy/cozy-flagship-app pull request #638
Opened 2023-03-03 15:37 UTC by doubleface

This patch will handle 303 response on download when using the local stack with a http url and not https.

An issue has been created on the react-native-fs : https://github.com/itinance/react-native-fs/pull/1153

#### Checklist

Before merging this PR, the following things must have been done:

* [ ] Faithful integration of the mockups at all screen sizes
* [ ] Tested on iOS
* [X] Tested on Android
* [ ] Localized in English and French
* [ ] All changes have test coverage
* [ ] Updated README & CHANGELOG, if necessary

2023-03-05 15:46 UTC, Ldoppea requested changes
Your patch contains way too many lines, it should contains only something like:
```diff
--- a/node_modules/react-native-fs/android/src/main/java/com/rnfs/Downloader.java
+++ b/node_modules/react-native-fs/android/src/main/java/com/rnfs/Downloader.java
@@ -67,6 +67,7 @@ public class Downloader extends AsyncTask<DownloadParams, long[], DownloadResult
         (
           statusCode == HttpURLConnection.HTTP_MOVED_PERM ||
           statusCode == HttpURLConnection.HTTP_MOVED_TEMP ||
+          statusCode == HttpURLConnection.HTTP_SEE_OTHER ||
           statusCode == 307 ||
           statusCode == 308
         )
```

It seems like your node_modules were not up-to-date when you run the patch command.

If you do a `yarn install` and run the patch command again it should generate the correct diff file.

2023-03-06 08:43 UTC, doubleface commented
@Ldoppea I generated it with patch-package. Now I modified it manually to only let what is wanted

2023-03-06 10:17 UTC, doubleface commented
@Ldoppea Now the current patch is generated after a 

```
rm -rf node_modules && yarn install
```

And this output the correct patch

2023-03-06 10:26 UTC, Ldoppea approved these changes

2023-03-06 10:26 UTC, Ldoppea commented
Nice :)

2023-03-06 10:49 UTC, merged